### PR TITLE
Fix root build.sbt set up.

### LINKED ISSUE #40: root build.sbt is not inherited by projects
When I set things up I assumed the root `build.sbt` file's settings would apply to all projects. As @mpilquist points out, this isn't the case.

We should make sure all shared settings are actually shared.

### PR DESCRIPTION
**Pull request by non**
This change means that subprojects will inherit the root
build.sbt settings. Since this was always the intention,
this fixes the build.

Resolves #40.

### CODE REVIEW

**Comment by non** [comment]
Review by @mpilquist, @tixxit, et al.

**Comment by mpilquist** [comment]
:+1:

**Comment by johnynek** [comment]
I really don't know sbt well enough to review this. Looks fine, but I am a terrible sbt cargo culter.

**Comment by non** [comment]
Fair enough. @tixxit?

**Comment by stew** [comment]
:+1:

**Pull request merged**
