### PR TITLE
typo: Rig -> Ring

### PR DESCRIPTION
**Pull request by dckc**

### CODE REVIEW

**Comment by non** [comment]
This isn't a typo. If you look you'll see `CommutativeRing` below. We have support for both *rigs* and *rings*.

**Comment by johnynek** [comment]
so good! I love this PR. I hope we keep getting it!

(also, `Rng` fixes welcome).

**Comment by dckc** [comment]
Oh. Learn something new every day. Wikipedia says "The term rig is also used occasionally ..." under Semiring. Any particular reason not to use "semiring"?

**Comment by dckc** [comment]
Ah. semiring has 1.

**Comment by tixxit** [comment]
Yeah - we use Semiring to mean a Ring without an inverse or a multiplicative identity. I think that Semiring is often used for both these cases, with the context in which it's used disambiguating it. However, we need both so we disambiguate them all with Semiring (no multiplicative identity, no inverse), Rig (no inverse), Rng (no multiplicative identity), and Ring :)

**Pull request closed without merging**
