### PR TITLE
Typo fixes in comments

### PR DESCRIPTION
**Pull request by pleira**

### CODE REVIEW

**Comment by non** [comment]
Good catch, thanks! :+1:

**Comment by non** [comment]
I'm going to wait for another +1. In Cats we have a policy that documentation-only fixes (especially ones like this that involve fixing typos, etc) can be merged immediately. How do folks here feel about that?

**Comment by johnynek** [comment]
:+1: and :+1: to doc-only changes not needing a second review (honestly, I thought we moved to one +1 for this project for everything).

**Comment by non** [comment]
You're right, we did, I had forgotten! :blush:

**Pull request merged**
