### PR TITLE
Should improve the workflow when releasing to Sonatype.

### PR DESCRIPTION
**Pull request by non**
This commit adds sbt-sonatype. It also updates our test
library dependencies to the most recent versions and
cleans up the SBT config a bit.

### CODE REVIEW

**Comment by non** [comment]
NOTE: I haven't actually published algebra with this setup yet, but I've used a very similar set up to publish at least 4 other projects today, so I'm fairly confident it will work.

**Comment by non** [comment]
P.S. I learned the hard way that the sort of setup we already have (with sbt-release) does not necessarily work well with sbt-scalajs: https://github.com/InTheNow/sbt-scalajs/issues/19

**Comment by tixxit** [comment]
:+1:

**Comment by InTheNow** [comment]
Also, discipline is not released, despite https://github.com/typelevel/discipline/pull/13

**Comment by non** [comment]
This PR is subsumed by #73.

**Pull request closed without merging**
